### ISSUE TITLE
[Question/Suggestion] Issue with claiming large area of land around terrain for players.

### ISSUE THREAD

**Issue by Rentai** [FabioZumbi12/Sponge-RedProtect#2]
This is probably something that will be declined,
but I was wondering if there was an easier way to claim for the players. Maybe similar to how admins claim.

Right now if people want to claim a decent area of land, they either have to dig up the entire area so its flat OR they need to claim 80 + blocks in the air at times above all terrain (this is usually if they are claiming around mountains, etc.

To be quite honest.. the claiming technique in this plugin is more of a hassle than others we have used/seen. 

example of how they would have to claim (glass would = fencing);
http://imgur.com/a/n5ul9

I just feel that since the square/rectangle has to be so precise in order to work with the sign.. that a lot of users are going to have issues. It's simple if you plan to make a small claim, but tiny things such as the land being 2 different heights, or blocks touching and so on can screw the claiming system up quite a bit.

Left clicking, then right clicking with a tool would be amazingggggggggg for player regions.

I'll be honest, I'm fighting for this because Red Protect is actually really fucking amazing.

**Comment by FabioZumbi12** [comment]
I think can be closed too. Added Method 2 for protect regions.
