### ISSUE TITLE
[Suggestion] Global Region Block placement restriction / blacklist

### ISSUE THREAD

**Issue by Rentai** [FabioZumbi12/Sponge-RedProtect#3]
This would make me switch over and use red protect 100 over other claiming/region plugins.
You have brought us the ability to seize explosions, fire spread and such, but I feel block placement would also be fantastic to have world wide.

- lava
- specific mod items
- obsidian
etc

This would then allow users to only user say lava and obsidian in their own regions/claims.

**Comment by FabioZumbi12** [comment]
You mean, with globalflag **build** on true, deny players to use this blocks right?

**Comment by Rentai** [comment]
Correct.
For example I am using essentialscmds right now for /blacklist and it keeps players from placing assigned items in both wilderness and their claims.

Would be nice if we could assign what they can't place in the wilderness AND what they can't place in their claims.

For example, lava can be used for massive grieifing in the wilderness, I wouldn't want them to place it in the wild. However, in their claims they can. Now, pixelmon (mod) has specific items that I wouldn't users to be able to place or use in their claims or in the wilderness.

Hope that makes sense. Thank you for reading

**Comment by FabioZumbi12** [comment]
I already added this on Bukkit version, but on Sponge i need to fix the actual issues to add more features, but yes, i will add this for Sponge too ;)

**Comment by Rentai** [comment]
Added and works perfectly. Closing now
